version: '3'

services:
  nextcloud:
    image: nextcloud:apache
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${NEXTCLOUD_DB}
      - POSTGRES_USER=${NEXTCLOUD_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=gertru.n8nonina.es
    volumes:
      - ./nextcloud/data:/var/www/html
    networks:
      - docker-apps-n8n_n8n-network  # Nombre correcto de la red

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${NEXTCLOUD_DB}
      - POSTGRES_USER=${NEXTCLOUD_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - docker-apps-n8n_n8n-network  # Nombre correcto de la red

# Usar red externa existente
networks:
  docker-apps-n8n_n8n-network:
    external: true  # Indica que la red ya existe

volumes:
  db_data:
