version: '3.8'  # Actualizar a la última versión estable

services:
  nextcloud:
    image: nextcloud:apache
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${NEXTCLOUD_DB}
      - POSTGRES_USER=${NEXTCLOUD_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=gertru.n8nonina.es
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_LIMIT=512M
    volumes:
      - nextcloud_data:/var/www/html
      - ./custom_apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
    networks:
      - docker-apps-n8n_n8n-network
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${NEXTCLOUD_DB}
      - POSTGRES_USER=${NEXTCLOUD_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres-backup:/backup
    networks:
      - docker-apps-n8n_n8n-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${NEXTCLOUD_USER} -d ${NEXTCLOUD_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - docker-apps-n8n_n8n-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  docker-apps-n8n_n8n-network:
    external: true

volumes:
  nextcloud_data:
  db_data:
  redis_data:
