version: '3'

services:
  nextcloud:
    image: nextcloud:apache
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${NEXTCLOUD_DB}
      - POSTGRES_USER=${NEXTCLOUD_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=gertru.n8nonina.es
    volumes:
      - ./nextcloud/data:/var/www/html
    networks:
      - nextcloud_network

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${NEXTCLOUD_DB}
      - POSTGRES_USER=${NEXTCLOUD_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - nextcloud_network

networks:
  nextcloud_network:
    driver: bridge

volumes:
  db_data:
